/*
 * Ri-Hub API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.9.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Authorization;
using BackendAPI.Models;

namespace BackendAPI.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class PaymentApiController : ControllerBase
    { 
        /// <summary>
        /// Create Checkout Session
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Successful Response</response>
        /// <response code="422">Validation Error</response>
        [HttpPost]
        [Route("/rehub/payment/create-stripe-checkout-session")]
        //[Authorize(AuthenticationSchemes = BearerAuthenticationHandler.SchemeName)]
        //[ValidateModelState]
        [SwaggerOperation("CreateCheckoutSessionPaymentCreateStripeCheckoutSessionPost")]
        [SwaggerResponse(statusCode: 200, type: typeof(RedirectUrl), description: "Successful Response")]
        [SwaggerResponse(statusCode: 422, type: typeof(HTTPValidationError), description: "Validation Error")]
        public virtual IActionResult CreateCheckoutSessionPaymentCreateStripeCheckoutSessionPost([FromBody]PaymentDataIn body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(RedirectUrl));

            //TODO: Uncomment the next line to return response 422 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(422, default(HTTPValidationError));
            string exampleJson = null;
            exampleJson = "{\r\n  \"url\" : \"\"\r\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<RedirectUrl>(exampleJson)
                        : default(RedirectUrl);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Get Lesson Packages
        /// </summary>
        /// <response code="200">Successful Response</response>
        [HttpGet]
        [Route("/rehub/payment/get-lesson-packages")]
        //[Authorize(AuthenticationSchemes = BearerAuthenticationHandler.SchemeName)]
        //[ValidateModelState]
        [SwaggerOperation("GetLessonPackagesPaymentGetLessonPackagesGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(Object), description: "Successful Response")]
        public virtual IActionResult GetLessonPackagesPaymentGetLessonPackagesGet()
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(Object));
            string exampleJson = null;
            exampleJson = "\"\"";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<Object>(exampleJson)
                        : default(Object);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Validate Payment
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Successful Response</response>
        /// <response code="422">Validation Error</response>
        [HttpPost]
        [Route("/rehub/payment/validate-payment")]
        //[Authorize(AuthenticationSchemes = BearerAuthenticationHandler.SchemeName)]
        //[ValidateModelState]
        [SwaggerOperation("ValidatePaymentPaymentValidatePaymentPost")]
        [SwaggerResponse(statusCode: 200, type: typeof(PaymentDataOut), description: "Successful Response")]
        [SwaggerResponse(statusCode: 422, type: typeof(HTTPValidationError), description: "Validation Error")]
        public virtual IActionResult ValidatePaymentPaymentValidatePaymentPost([FromBody]PaymentDataIn body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(PaymentDataOut));

            //TODO: Uncomment the next line to return response 422 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(422, default(HTTPValidationError));
            string exampleJson = null;
            exampleJson = "{\r\n  \"cost\" : \"\",\r\n  \"lessons_num\" : \"\",\r\n  \"discount\" : \"\",\r\n  \"lesson_package_name\" : \"\"\r\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<PaymentDataOut>(exampleJson)
                        : default(PaymentDataOut);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Webhook
        /// </summary>
        /// <response code="200">Successful Response</response>
        [HttpPost]
        [Route("/rehub/payment/stripe-webhook")]
        //[ValidateModelState]
        [SwaggerOperation("WebhookPaymentStripeWebhookPost")]
        [SwaggerResponse(statusCode: 200, type: typeof(Object), description: "Successful Response")]
        public virtual IActionResult WebhookPaymentStripeWebhookPost()
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(Object));
            string exampleJson = null;
            exampleJson = "\"\"";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<Object>(exampleJson)
                        : default(Object);            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
