/*
 * Ri-Hub API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.9.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace BackendAPI.Models
{
  
          /// <summary>
          /// An enumeration.
          /// </summary>
          /// <value>An enumeration.</value>
          [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
          public enum AppointmentStatusType
          {
              /// <summary>
              /// Enum PendingEnum for pending
              /// </summary>
              [EnumMember(Value = "pending")]
              PendingEnum = 0,
              /// <summary>
              /// Enum ActiveEnum for active
              /// </summary>
              [EnumMember(Value = "active")]
              ActiveEnum = 1,
              /// <summary>
              /// Enum FinishedEnum for finished
              /// </summary>
              [EnumMember(Value = "finished")]
              FinishedEnum = 2,
              /// <summary>
              /// Enum MissedEnum for missed
              /// </summary>
              [EnumMember(Value = "missed")]
              MissedEnum = 3          }
}
