/*
 * Ri-Hub API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.9.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace BackendAPI.Models
{
  
          /// <summary>
          /// An enumeration.
          /// </summary>
          /// <value>An enumeration.</value>
          [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
          public enum GenderType
          {
              /// <summary>
              /// Enum MaleEnum for male
              /// </summary>
              [EnumMember(Value = "male")]
              MaleEnum = 0,
              /// <summary>
              /// Enum FemaleEnum for female
              /// </summary>
              [EnumMember(Value = "female")]
              FemaleEnum = 1,
              /// <summary>
              /// Enum OtherEnum for other
              /// </summary>
              [EnumMember(Value = "other")]
              OtherEnum = 2,
              /// <summary>
              /// Enum Empty for null
              /// </summary>
              [EnumMember(Value = null)]
              Empty = 3          }
}
