/*
 * Ri-Hub API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.9.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace BackendAPI.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class NotificationCreate : IEquatable<NotificationCreate>
    { 
        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [Required]

        [DataMember(Name="message")]
        public Object Message { get; set; }

        /// <summary>
        /// Gets or Sets RecipientTypes
        /// </summary>
        [Required]

        [DataMember(Name="recipient_types")]
        public Object RecipientTypes { get; set; }

        /// <summary>
        /// Gets or Sets RecipientIds
        /// </summary>

        [DataMember(Name="recipient_ids")]
        public Object RecipientIds { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class NotificationCreate {\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  RecipientTypes: ").Append(RecipientTypes).Append("\n");
            sb.Append("  RecipientIds: ").Append(RecipientIds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((NotificationCreate)obj);
        }

        /// <summary>
        /// Returns true if NotificationCreate instances are equal
        /// </summary>
        /// <param name="other">Instance of NotificationCreate to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(NotificationCreate other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Message == other.Message ||
                    Message != null &&
                    Message.Equals(other.Message)
                ) && 
                (
                    RecipientTypes == other.RecipientTypes ||
                    RecipientTypes != null &&
                    RecipientTypes.Equals(other.RecipientTypes)
                ) && 
                (
                    RecipientIds == other.RecipientIds ||
                    RecipientIds != null &&
                    RecipientIds.Equals(other.RecipientIds)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Message != null)
                    hashCode = hashCode * 59 + Message.GetHashCode();
                    if (RecipientTypes != null)
                    hashCode = hashCode * 59 + RecipientTypes.GetHashCode();
                    if (RecipientIds != null)
                    hashCode = hashCode * 59 + RecipientIds.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(NotificationCreate left, NotificationCreate right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(NotificationCreate left, NotificationCreate right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
