/*
 * Ri-Hub API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.9.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace BackendAPI.Models
{
  
          /// <summary>
          /// An enumeration.
          /// </summary>
          /// <value>An enumeration.</value>
          [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
          public enum PathologyType
          {
              /// <summary>
              /// Enum NUMBER_1 for pathology_1
              /// </summary>
              [EnumMember(Value = "pathology_1")]
              NUMBER_1 = 0,
              /// <summary>
              /// Enum NUMBER_2 for pathology_2
              /// </summary>
              [EnumMember(Value = "pathology_2")]
              NUMBER_2 = 1,
              /// <summary>
              /// Enum NUMBER_3 for pathology_3
              /// </summary>
              [EnumMember(Value = "pathology_3")]
              NUMBER_3 = 2,
              /// <summary>
              /// Enum NUMBER_4 for pathology_4
              /// </summary>
              [EnumMember(Value = "pathology_4")]
              NUMBER_4 = 3,
              /// <summary>
              /// Enum NUMBER_5 for pathology_5
              /// </summary>
              [EnumMember(Value = "pathology_5")]
              NUMBER_5 = 4,
              /// <summary>
              /// Enum NUMBER_6 for pathology_6
              /// </summary>
              [EnumMember(Value = "pathology_6")]
              NUMBER_6 = 5          }
}
