/*
 * Ri-Hub API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.9.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace BackendAPI.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class PaymentDataIn : IEquatable<PaymentDataIn>
    { 
        /// <summary>
        /// Gets or Sets LessonPackageId
        /// </summary>
        [Required]

        [DataMember(Name="lesson_package_id")]
        public Object LessonPackageId { get; set; }

        /// <summary>
        /// Gets or Sets DiscountCouponName
        /// </summary>

        [DataMember(Name="discount_coupon_name")]
        public Object DiscountCouponName { get; set; }

        /// <summary>
        /// Gets or Sets PaymentProcessor
        /// </summary>

        [DataMember(Name="payment_processor")]
        public PaymentProcessorType PaymentProcessor { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PaymentDataIn {\n");
            sb.Append("  LessonPackageId: ").Append(LessonPackageId).Append("\n");
            sb.Append("  DiscountCouponName: ").Append(DiscountCouponName).Append("\n");
            sb.Append("  PaymentProcessor: ").Append(PaymentProcessor).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((PaymentDataIn)obj);
        }

        /// <summary>
        /// Returns true if PaymentDataIn instances are equal
        /// </summary>
        /// <param name="other">Instance of PaymentDataIn to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PaymentDataIn other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    LessonPackageId == other.LessonPackageId ||
                    LessonPackageId != null &&
                    LessonPackageId.Equals(other.LessonPackageId)
                ) && 
                (
                    DiscountCouponName == other.DiscountCouponName ||
                    DiscountCouponName != null &&
                    DiscountCouponName.Equals(other.DiscountCouponName)
                ) && 
                (
                    PaymentProcessor == other.PaymentProcessor ||
                    PaymentProcessor != null &&
                    PaymentProcessor.Equals(other.PaymentProcessor)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (LessonPackageId != null)
                    hashCode = hashCode * 59 + LessonPackageId.GetHashCode();
                    if (DiscountCouponName != null)
                    hashCode = hashCode * 59 + DiscountCouponName.GetHashCode();
                    if (PaymentProcessor != null)
                    hashCode = hashCode * 59 + PaymentProcessor.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(PaymentDataIn left, PaymentDataIn right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(PaymentDataIn left, PaymentDataIn right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
