/*
 * Ri-Hub API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.9.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace BackendAPI.Models
{
  
          /// <summary>
          /// An enumeration.
          /// </summary>
          /// <value>An enumeration.</value>
          [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
          public enum UserType
          {
              /// <summary>
              /// Enum AdminEnum for admin
              /// </summary>
              [EnumMember(Value = "admin")]
              AdminEnum = 0,
              /// <summary>
              /// Enum DoctorEnum for doctor
              /// </summary>
              [EnumMember(Value = "doctor")]
              DoctorEnum = 1,
              /// <summary>
              /// Enum ClientEnum for client
              /// </summary>
              [EnumMember(Value = "client")]
              ClientEnum = 2          }
}
