// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReHub.Db.PostgreSQL;

#nullable disable

namespace ReHub.DbDataModel.Migrations
{
    [DbContext(typeof(PostgresDbContext))]
    partial class PostgresDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReHub.DbDataModel.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("MaxListeners")
                        .HasColumnType("integer")
                        .HasColumnName("max_listeners");

                    b.Property<int?>("SpeakerId")
                        .HasColumnType("integer")
                        .HasColumnName("speaker_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("interval")
                        .HasColumnName("time");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("SpeakerId");

                    b.ToTable("appointments");
                });

            modelBuilder.Entity("ReHub.DbDataModel.Models.AppointmentClient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("integer")
                        .HasColumnName("appointment_id");

                    b.Property<int?>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<int?>("PainRateAfter")
                        .HasColumnType("integer")
                        .HasColumnName("pain_rate_after");

                    b.Property<int?>("PainRateBefore")
                        .HasColumnType("integer")
                        .HasColumnName("pain_rate_before");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("ClientId");

                    b.ToTable("appointment_clients");
                });

            modelBuilder.Entity("ReHub.DbDataModel.Models.ClientDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("BirthCity")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("BirthCountry")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("FiscalCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int?>("Pathology")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("client_details");
                });

            modelBuilder.Entity("ReHub.DbDataModel.Models.Conference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChannelAdminId")
                        .HasColumnType("integer")
                        .HasColumnName("channel_admin_id");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel_name");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ChannelAdminId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("conference");
                });

            modelBuilder.Entity("ReHub.DbDataModel.Models.ConferenceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<int?>("ActorId")
                        .HasColumnType("integer")
                        .HasColumnName("actor_id");

                    b.Property<int?>("ConferenceId")
                        .HasColumnType("integer")
                        .HasColumnName("conference_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("ConferenceId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("conference_history");
                });

            modelBuilder.Entity("ReHub.DbDataModel.Models.CouponUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<int>("CouponId")
                        .HasColumnType("integer")
                        .HasColumnName("coupon_id");

                    b.Property<int>("UseCount")
                        .HasColumnType("integer")
                        .HasColumnName("use_count");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CouponId");

                    b.ToTable("coupon_users");
                });

            modelBuilder.Entity("ReHub.DbDataModel.Models.DiscountCoupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("integer");

                    b.Property<int>("CouponType")
                        .HasColumnType("integer")
                        .HasColumnName("coupon_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double>("Discount")
                        .HasColumnType("double precision")
                        .HasColumnName("discount");

                    b.Property<int>("DiscountType")
                        .HasColumnType("integer")
                        .HasColumnName("discount_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime>("ValidityUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("validity_until");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("discount_coupons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CouponType = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 5.0,
                            DiscountType = 0,
                            Name = "SALE",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidityUntil = new DateTime(2024, 6, 12, 13, 54, 31, 878, DateTimeKind.Utc).AddTicks(2040)
                        },
                        new
                        {
                            Id = 2,
                            CouponType = 0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 1.0,
                            DiscountType = 1,
                            Name = "FIX",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidityUntil = new DateTime(2024, 6, 12, 13, 54, 31, 878, DateTimeKind.Utc).AddTicks(2047)
                        });
                });

            modelBuilder.Entity("ReHub.DbDataModel.Models.LessonPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Cost")
                        .HasColumnType("double precision")
                        .HasColumnName("cost");

                    b.Property<int>("LessonsNum")
                        .HasColumnType("integer")
                        .HasColumnName("lessons_num");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("lesson_packages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 9.9000000000000004,
                            LessonsNum = 1,
                            Name = "PACKAGE NAME N.001"
                        },
                        new
                        {
                            Id = 2,
                            Cost = 44.899999999999999,
                            LessonsNum = 5,
                            Name = "PACKAGE NAME N.002"
                        },
                        new
                        {
                            Id = 3,
                            Cost = 79.900000000000006,
                            LessonsNum = 10,
                            Name = "PACKAGE NAME N.003"
                        });
                });

            modelBuilder.Entity("ReHub.DbDataModel.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer")
                        .HasColumnName("sender_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SenderId");

                    b.HasIndex("UserId");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("ReHub.DbDataModel.Models.NotificationRecipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("NotificationId")
                        .HasColumnType("integer")
                        .HasColumnName("notification_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<bool?>("UserSeen")
                        .HasColumnType("boolean")
                        .HasColumnName("user_seen");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("notification_recipients");
                });

            modelBuilder.Entity("ReHub.DbDataModel.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("double precision")
                        .HasColumnName("amount");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<int?>("CouponId")
                        .HasColumnType("integer")
                        .HasColumnName("coupon_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("LessonPackageId")
                        .HasColumnType("integer")
                        .HasColumnName("lesson_package_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CouponId");

                    b.HasIndex("LessonPackageId");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("ReHub.DbDataModel.Models.ReferrerDoctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ReferralCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("referral_code");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ReferralCode")
                        .IsUnique();

                    b.ToTable("referrer_doctors");
                });

            modelBuilder.Entity("ReHub.DbDataModel.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("users");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ReHub.DbDataModel.Models.Admin", b =>
                {
                    b.HasBaseType("ReHub.DbDataModel.Models.User");

                    b.ToTable("admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarUrl = "test",
                            CreatedAt = new DateTime(2024, 5, 13, 13, 54, 31, 878, DateTimeKind.Utc).AddTicks(1693),
                            Deleted = false,
                            Email = "9iYms6TCxuISbWFyaW96NjNAZ21haWwuY29t",
                            Gender = 0,
                            IsVerified = true,
                            Name = "Mario",
                            Password = "9iYms6TCxuIJMTIzNDU2Nzg5",
                            Surname = "Z.",
                            Type = 0,
                            UpdatedAt = new DateTime(2024, 5, 13, 13, 54, 31, 878, DateTimeKind.Utc).AddTicks(1694)
                        });
                });

            modelBuilder.Entity("ReHub.DbDataModel.Models.Client", b =>
                {
                    b.HasBaseType("ReHub.DbDataModel.Models.User");

                    b.Property<int>("Balance")
                        .HasColumnType("integer");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReferrerId")
                        .HasColumnType("integer");

                    b.Property<int>("SubType")
                        .HasColumnType("integer");

                    b.HasIndex("DoctorId");

                    b.HasIndex("ReferrerId");

                    b.ToTable("clients");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 5, 13, 13, 54, 31, 878, DateTimeKind.Utc).AddTicks(1979),
                            Deleted = false,
                            Email = "9iYms6TCxuIRdGVzdDFAZXhhbXBsZS5jb20=",
                            Gender = 3,
                            IsVerified = false,
                            Name = "Test01",
                            Password = "9iYms6TCxuIJMTIzNDU2Nzg5",
                            Surname = "Test01",
                            Type = 0,
                            UpdatedAt = new DateTime(2024, 5, 13, 13, 54, 31, 878, DateTimeKind.Utc).AddTicks(1980),
                            Balance = 0,
                            SubType = 0
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 5, 13, 13, 54, 31, 878, DateTimeKind.Utc).AddTicks(1982),
                            Deleted = false,
                            Email = "9iYms6TCxuIRdGVzdDJAZXhhbXBsZS5jb20=",
                            Gender = 3,
                            IsVerified = false,
                            Name = "Test02",
                            Password = "9iYms6TCxuIJMTIzNDU2Nzg5",
                            Surname = "Test02",
                            Type = 0,
                            UpdatedAt = new DateTime(2024, 5, 13, 13, 54, 31, 878, DateTimeKind.Utc).AddTicks(1982),
                            Balance = 0,
                            SubType = 0
                        });
                });

            modelBuilder.Entity("ReHub.DbDataModel.Models.Doctor", b =>
                {
                    b.HasBaseType("ReHub.DbDataModel.Models.User");

                    b.Property<string>("About")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SubType")
                        .HasColumnType("integer");

                    b.ToTable("doctors");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            AvatarUrl = "https://static.wikia.nocookie.net/rickandmorty/images/3/3f/Young_Adult_Rick.png",
                            CreatedAt = new DateTime(2024, 5, 13, 13, 54, 31, 878, DateTimeKind.Utc).AddTicks(1949),
                            Deleted = false,
                            Email = "9iYms6TCxuITZG9jdG9yMUBleGFtcGxlLmNvbQ==",
                            Gender = 0,
                            IsVerified = true,
                            Name = "Rick",
                            Password = "9iYms6TCxuIJMTIzNDU2Nzg5",
                            Surname = "Sanchez",
                            Type = 1,
                            UpdatedAt = new DateTime(2024, 5, 13, 13, 54, 31, 878, DateTimeKind.Utc).AddTicks(1949),
                            About = "Text about doctor #3",
                            SubType = 1
                        },
                        new
                        {
                            Id = 3,
                            AvatarUrl = "https://static.wikia.nocookie.net/marveldatabase/images/0/02/Adam_Warlock_%28Earth-829%29_from_Hercules_Vol_2_3_0001.jpg",
                            CreatedAt = new DateTime(2024, 5, 13, 13, 54, 31, 878, DateTimeKind.Utc).AddTicks(1953),
                            Deleted = false,
                            Email = "9iYms6TCxuITZG9jdG9yMkBleGFtcGxlLmNvbQ==",
                            Gender = 0,
                            IsVerified = false,
                            Name = "Adam",
                            Password = "9iYms6TCxuIJMTIzNDU2Nzg5",
                            Surname = "Warlock",
                            Type = 1,
                            UpdatedAt = new DateTime(2024, 5, 13, 13, 54, 31, 878, DateTimeKind.Utc).AddTicks(1953),
                            About = "Text about doctor #4",
                            SubType = 1
                        });
                });

            modelBuilder.Entity("ReHub.DbDataModel.Models.Appointment", b =>
                {
                    b.HasOne("ReHub.DbDataModel.Models.Client", null)
                        .WithMany("Appointments")
                        .HasForeignKey("ClientId");

                    b.HasOne("ReHub.DbDataModel.Models.Doctor", "Speaker")
                        .WithMany("Appointments")
                        .HasForeignKey("SpeakerId");

                    b.Navigation("Speaker");
                });

            modelBuilder.Entity("ReHub.DbDataModel.Models.AppointmentClient", b =>
                {
                    b.HasOne("ReHub.DbDataModel.Models.Appointment", "Appointment")
                        .WithMany("AppointmentClients")
                        .HasForeignKey("AppointmentId");

                    b.HasOne("ReHub.DbDataModel.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.Navigation("Appointment");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ReHub.DbDataModel.Models.ClientDetails", b =>
                {
                    b.HasOne("ReHub.DbDataModel.Models.Client", "Client")
                        .WithOne("ClientDetails")
                        .HasForeignKey("ReHub.DbDataModel.Models.ClientDetails", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ReHub.DbDataModel.Models.Conference", b =>
                {
                    b.HasOne("ReHub.DbDataModel.Models.User", "ChannelAdmin")
                        .WithMany()
                        .HasForeignKey("ChannelAdminId");

                    b.HasOne("ReHub.DbDataModel.Models.Doctor", null)
                        .WithMany("AdministratedChannels")
                        .HasForeignKey("DoctorId");

                    b.Navigation("ChannelAdmin");
                });

            modelBuilder.Entity("ReHub.DbDataModel.Models.ConferenceHistory", b =>
                {
                    b.HasOne("ReHub.DbDataModel.Models.User", "Actor")
                        .WithMany("ConferenceActions")
                        .HasForeignKey("ActorId");

                    b.HasOne("ReHub.DbDataModel.Models.Conference", "Conference")
                        .WithMany("ConferenceHistories")
                        .HasForeignKey("ConferenceId");

                    b.Navigation("Actor");

                    b.Navigation("Conference");
                });

            modelBuilder.Entity("ReHub.DbDataModel.Models.CouponUser", b =>
                {
                    b.HasOne("ReHub.DbDataModel.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReHub.DbDataModel.Models.DiscountCoupon", "Coupon")
                        .WithMany("CouponUsers")
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Coupon");
                });

            modelBuilder.Entity("ReHub.DbDataModel.Models.DiscountCoupon", b =>
                {
                    b.HasOne("ReHub.DbDataModel.Models.Client", null)
                        .WithMany("UsedCoupons")
                        .HasForeignKey("ClientId");
                });

            modelBuilder.Entity("ReHub.DbDataModel.Models.Notification", b =>
                {
                    b.HasOne("ReHub.DbDataModel.Models.User", "Sender")
                        .WithMany("NotificationsForUser")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReHub.DbDataModel.Models.User", null)
                        .WithMany("NotificationsFromUser")
                        .HasForeignKey("UserId");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("ReHub.DbDataModel.Models.NotificationRecipient", b =>
                {
                    b.HasOne("ReHub.DbDataModel.Models.Notification", "Notification")
                        .WithMany("NotificationRecipients")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReHub.DbDataModel.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReHub.DbDataModel.Models.Payment", b =>
                {
                    b.HasOne("ReHub.DbDataModel.Models.Client", "Client")
                        .WithMany("Payments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReHub.DbDataModel.Models.DiscountCoupon", "Coupon")
                        .WithMany("Payments")
                        .HasForeignKey("CouponId");

                    b.HasOne("ReHub.DbDataModel.Models.LessonPackage", "LessonPackage")
                        .WithMany("Payments")
                        .HasForeignKey("LessonPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Coupon");

                    b.Navigation("LessonPackage");
                });

            modelBuilder.Entity("ReHub.DbDataModel.Models.Admin", b =>
                {
                    b.HasOne("ReHub.DbDataModel.Models.User", null)
                        .WithOne()
                        .HasForeignKey("ReHub.DbDataModel.Models.Admin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReHub.DbDataModel.Models.Client", b =>
                {
                    b.HasOne("ReHub.DbDataModel.Models.Doctor", "Doctor")
                        .WithMany("Clients")
                        .HasForeignKey("DoctorId");

                    b.HasOne("ReHub.DbDataModel.Models.User", null)
                        .WithOne()
                        .HasForeignKey("ReHub.DbDataModel.Models.Client", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReHub.DbDataModel.Models.ReferrerDoctor", "Referrer")
                        .WithMany("Clients")
                        .HasForeignKey("ReferrerId");

                    b.Navigation("Doctor");

                    b.Navigation("Referrer");
                });

            modelBuilder.Entity("ReHub.DbDataModel.Models.Doctor", b =>
                {
                    b.HasOne("ReHub.DbDataModel.Models.User", null)
                        .WithOne()
                        .HasForeignKey("ReHub.DbDataModel.Models.Doctor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReHub.DbDataModel.Models.Appointment", b =>
                {
                    b.Navigation("AppointmentClients");
                });

            modelBuilder.Entity("ReHub.DbDataModel.Models.Conference", b =>
                {
                    b.Navigation("ConferenceHistories");
                });

            modelBuilder.Entity("ReHub.DbDataModel.Models.DiscountCoupon", b =>
                {
                    b.Navigation("CouponUsers");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("ReHub.DbDataModel.Models.LessonPackage", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("ReHub.DbDataModel.Models.Notification", b =>
                {
                    b.Navigation("NotificationRecipients");
                });

            modelBuilder.Entity("ReHub.DbDataModel.Models.ReferrerDoctor", b =>
                {
                    b.Navigation("Clients");
                });

            modelBuilder.Entity("ReHub.DbDataModel.Models.User", b =>
                {
                    b.Navigation("ConferenceActions");

                    b.Navigation("NotificationsForUser");

                    b.Navigation("NotificationsFromUser");
                });

            modelBuilder.Entity("ReHub.DbDataModel.Models.Client", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("ClientDetails")
                        .IsRequired();

                    b.Navigation("Payments");

                    b.Navigation("UsedCoupons");
                });

            modelBuilder.Entity("ReHub.DbDataModel.Models.Doctor", b =>
                {
                    b.Navigation("AdministratedChannels");

                    b.Navigation("Appointments");

                    b.Navigation("Clients");
                });
#pragma warning restore 612, 618
        }
    }
}
